### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by marianoarga** [restcord/restcord#10]
Hello, could you please help me with the installation? It says this when running "composer require restcord/restcord"

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - The requested package restcord/restcord No version set (parsed as 1.0.0) is satisfiable by restcord/restcord[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.
> 
> 
> Installation failed, reverting ./composer.json to its original content.

**Comment by marianoarga** [comment]
Fixed, I downloaded the compose.json an run "composer install" and then "composer require restcord/restcord".
The only command needed is "composer require restcord/restcord" in an empty folder.

**Comment by aequasi** [comment]
Make sure you check out the composer docs: https://getcomposer.org/doc/01-basic-usage.md
