### ISSUE TITLE
Validation errors: [avatar] must be of type avatar data string

### ISSUE THREAD

**Issue by bkuhl** [restcord/restcord#103]
I believe commit https://github.com/restcord/restcord/commit/c3b2810ab8b0029761e7ea7ab442f6157299e74f introduced a broken state into `master`.  By updating my composer.json file to depend on `"restcord/restcord": "dev-master#0c6f91ba70e43d41d94bf9d82ff43dc4d662be82",` I'm able to use `master` prior to these changes being merged in and webhook creation is once again successful.

The error I'm seeing is:

```
Validation errors: [avatar] must be of type avatar data string at /var/www/html/vendor/guzzlehttp/guzzle-services/src/Handler/ValidatedDescriptionHandler.php:76
```

My underlying code is:

```
            $discordWebhook = $this->discord->webhook->createWebhook([
                'channel.id'    => $channelId,
                'name'          => Webhook::webhookName(),
                'avatar'        => Webhook::webhookAvatar()
            ]);
```

```
    public static function webhookAvatar() : string
    {
        return 'data:image/png;base64,' . base64_encode(file_get_contents(public_path('/images/icon.png')));
    }
```

**Comment by cryptiklemur** [comment]
I dont suppose this is still an issue, is it?

**Comment by bkuhl** [comment]
Yep, this is fixed as of Oct 2020 - https://github.com/restcord/restcord/commit/711de39b850adc36d1e699800be8d1b206e4e6ba
