### ISSUE TITLE
Monolog 2.0 support?

### ISSUE THREAD

**Issue by JakeBooher** [restcord/restcord#105]
Using a library that require Monolog 2.0, so hard to fork it and make some tweaks to get it to work with 1.x to install restcord. Any chance of adding in support for Monolog 2.0? This should be possible to do while maintaining BC as Laravel 6 supports both versions

**Comment by aequasi** [comment]
https://github.com/restcord/restcord/blob/master/composer.json#L9

Dev-master already supports this, not currently tagging a release though

**Comment by molteber** [comment]
Is there a timeline for when there will be a tagged release for v2 support?

**Comment by relisiuol** [comment]
Up.

**Comment by molteber** [comment]
If you want to use it with monolog v2, @relisiuol, use the `dev-master` version for now

**Comment by Kaishiyoku** [comment]
RestCord is no longer working with Lumen v7 because of the Monolog ^2.0 dependency. The issue here is nearly 5 months old. Using dev-master for applications in production doesn't seem right. Is there any chance that there will be a version bump for monolog?

**Comment by mhayes14** [comment]
Also interested to know when the monolog version bump will be tagged.

**Comment by chescos** [comment]
@aequasi hey, any update on a new release? The latest version doesn't work with Laravel 7 and Lumen 7 due to the monolog conflict.

**Comment by bkuhl** [comment]
You can lock into a specific commit in your `composer.json` such as `"restcord/restcord": "dev-master#58d1baf41bf24d253ffd4bb393dd1e2bd660237e"`.
