### ISSUE TITLE
Return value of Guild::id() must be of the type int, string returned

### ISSUE THREAD

**Issue by Kanuuu** [restcord/restcord#108]
Error:
`Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_RECOVERABLE_ERROR)
Return value of LaravelRestcord\Discord\Guild::id() must be of the type int, string returned`

Guild.php:
`public function id() : int
    {
        return $this->id;
    }`

Code:
`/**
         * @var $guild Guild
         */
        foreach ($discord->guilds() as $guild) {
            if ($guild->id() === '536562056543993870') {
                dd($guild);
            }
        }`

**Comment by aequasi** [comment]
Are you on 64 bit php?
