### ISSUE TITLE
Leaveguild problem

### ISSUE THREAD

**Issue by StrangerGithuber** [restcord/restcord#109]
Hello
I can get the channels and members but I can't make the bot to leave the server when the owner click to the remove button.
I get this message when I am trying to use:

`There was an error executing the leaveGuild command: Client error: `DELETE https://discordapp.com/api/v6/users/@me/guilds/652119293600989196` resulted in a `400 BAD REQUEST``

The token is right used otherwise I couldn't get the guild channels and members so it can't be the problem.
I am trying to use this way:

`  $discordguild = new DiscordClient( [ 'token' => env( 'DISCORD_BOT_TOKEN' ) ] );
 $discordguild->user->leaveGuild(['guild.id' => (int)$guildid]);`

What is the problem?

**Comment by aequasi** [comment]
Can you catch the exception and log out the response body

**Comment by StrangerGithuber** [comment]
Hmm I am getting same. I put the code between try catch and I return the error message but I get the same message.

**Comment by aequasi** [comment]
You have to dig through and get the guzzle server exception

**Comment by StrangerGithuber** [comment]
Hmm which PHP version recommended? Documentation saying 7.0 and above but hmm now I have 7.4.1 which the newest xampp using.
I tried with guzzle's GuzzleHttp\Exception\ClientException but getting the same. Here is the full log file:
`[2020-01-27 22:29:23] local.ERROR: There was an error executing the leaveGuild command: Client error: `DELETE https://discordapp.com/api/v6/users/@me/guilds/652118692481466388` resulted in a `400 BAD REQUEST` response:

 {"userId":14,"exception":"[object] (GuzzleHttp\\Command\\Exception\\CommandClientException(code: 0): There was an error executing the leaveGuild command: Client error: `DELETE https://discordapp.com/api/v6/users/@me/guilds/652118692481466388` resulted in a `400 BAD REQUEST` response:

 at E:\\Projektek\\xyz\\vendor\\guzzlehttp\\command\\src\\Exception\\CommandException.php:57)
[stacktrace]
#0 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\command\\src\\ServiceClient.php(179): GuzzleHttp\\Command\\Exception\\CommandException::fromPrevious(Object(GuzzleHttp\\Command\\Command), Object(GuzzleHttp\\Exception\\ClientException))
#1 [internal function]: GuzzleHttp\\Command\\ServiceClient->GuzzleHttp\\Command\\{closure}()
#2 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\promises\\src\\Coroutine.php(142): Generator->throw(Object(GuzzleHttp\\Exception\\ClientException))
#3 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\promises\\src\\Promise.php(203): GuzzleHttp\\Promise\\Coroutine->_handleFailure(Object(GuzzleHttp\\Exception\\ClientException))
#4 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\promises\\src\\Promise.php(156): GuzzleHttp\\Promise\\Promise::callHandler(2, Object(GuzzleHttp\\Exception\\ClientException), Array)
#5 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\promises\\src\\TaskQueue.php(47): GuzzleHttp\\Promise\\Promise::GuzzleHttp\\Promise\\{closure}()
#6 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\guzzle\\src\\Handler\\CurlMultiHandler.php(118): GuzzleHttp\\Promise\\TaskQueue->run()
#7 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\guzzle\\src\\Handler\\CurlMultiHandler.php(145): GuzzleHttp\\Handler\\CurlMultiHandler->tick()
#8 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\promises\\src\\Promise.php(246): GuzzleHttp\\Handler\\CurlMultiHandler->execute(true)
#9 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\promises\\src\\Promise.php(223): GuzzleHttp\\Promise\\Promise->invokeWaitFn()
#10 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\promises\\src\\Promise.php(267): GuzzleHttp\\Promise\\Promise->waitIfPending()
#11 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\promises\\src\\Promise.php(225): GuzzleHttp\\Promise\\Promise->invokeWaitList()
#12 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\promises\\src\\Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()
#13 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\promises\\src\\Coroutine.php(65): GuzzleHttp\\Promise\\Promise->wait()
#14 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\promises\\src\\Promise.php(246): GuzzleHttp\\Promise\\Coroutine->GuzzleHttp\\Promise\\{closure}(true)
#15 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\promises\\src\\Promise.php(223): GuzzleHttp\\Promise\\Promise->invokeWaitFn()
#16 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\promises\\src\\Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()
#17 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\promises\\src\\Coroutine.php(85): GuzzleHttp\\Promise\\Promise->wait(true)
#18 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\command\\src\\ServiceClient.php(77): GuzzleHttp\\Promise\\Coroutine->wait()
#19 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\command\\src\\ServiceClient.php(153): GuzzleHttp\\Command\\ServiceClient->execute(Object(GuzzleHttp\\Command\\Command))
#20 E:\\Projektek\\xyz\\vendor\
estcord\
estcord\\src\\OverriddenGuzzleClient.php(86): GuzzleHttp\\Command\\ServiceClient->__call('leaveGuild', Array)
#21 E:\\Projektek\\xyz\\app\\Http\\Controllers\\ApiController.php(1402): RestCord\\OverriddenGuzzleClient->__call('leaveGuild', Array)
#22 [internal function]: App\\Http\\Controllers\\ApiController->myservers_delete(Object(Illuminate\\Http\\Request))
#23 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): call_user_func_array(Array, Array)
#24 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('myservers_delet...', Array)
#25 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\ApiController), 'myservers_delet...')
#26 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(176): Illuminate\\Routing\\Route->runController()
#27 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(681): Illuminate\\Routing\\Route->run()
#28 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\ThrottleRequests.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 60, '1')
#33 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Middleware\\Authenticate.php(43): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'api')
#35 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#37 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#38 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#39 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#40 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#41 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#42 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 E:\\Projektek\\xyz\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#54 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#55 E:\\Projektek\\xyz\\public\\index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#56 {main}

[previous exception] [object] (GuzzleHttp\\Exception\\ClientException(code: 400): Client error: `DELETE https://discordapp.com/api/v6/users/@me/guilds/652118692481466388` resulted in a `400 BAD REQUEST` response:

 at E:\\Projektek\\xyz\\vendor\\guzzlehttp\\guzzle\\src\\Exception\\RequestException.php:113)
[stacktrace]
#0 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\guzzle\\src\\Middleware.php(65): GuzzleHttp\\Exception\\RequestException::create(Object(GuzzleHttp\\Psr7\\Request), Object(GuzzleHttp\\Psr7\\Response))
#1 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\promises\\src\\Promise.php(203): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Response))
#2 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\promises\\src\\Promise.php(156): GuzzleHttp\\Promise\\Promise::callHandler(1, Object(GuzzleHttp\\Psr7\\Response), Array)
#3 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\promises\\src\\TaskQueue.php(47): GuzzleHttp\\Promise\\Promise::GuzzleHttp\\Promise\\{closure}()
#4 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\guzzle\\src\\Handler\\CurlMultiHandler.php(118): GuzzleHttp\\Promise\\TaskQueue->run()
#5 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\guzzle\\src\\Handler\\CurlMultiHandler.php(145): GuzzleHttp\\Handler\\CurlMultiHandler->tick()
#6 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\promises\\src\\Promise.php(246): GuzzleHttp\\Handler\\CurlMultiHandler->execute(true)
#7 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\promises\\src\\Promise.php(223): GuzzleHttp\\Promise\\Promise->invokeWaitFn()
#8 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\promises\\src\\Promise.php(267): GuzzleHttp\\Promise\\Promise->waitIfPending()
#9 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\promises\\src\\Promise.php(225): GuzzleHttp\\Promise\\Promise->invokeWaitList()
#10 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\promises\\src\\Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()
#11 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\promises\\src\\Coroutine.php(65): GuzzleHttp\\Promise\\Promise->wait()
#12 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\promises\\src\\Promise.php(246): GuzzleHttp\\Promise\\Coroutine->GuzzleHttp\\Promise\\{closure}(true)
#13 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\promises\\src\\Promise.php(223): GuzzleHttp\\Promise\\Promise->invokeWaitFn()
#14 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\promises\\src\\Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()
#15 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\promises\\src\\Coroutine.php(85): GuzzleHttp\\Promise\\Promise->wait(true)
#16 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\command\\src\\ServiceClient.php(77): GuzzleHttp\\Promise\\Coroutine->wait()
#17 E:\\Projektek\\xyz\\vendor\\guzzlehttp\\command\\src\\ServiceClient.php(153): GuzzleHttp\\Command\\ServiceClient->execute(Object(GuzzleHttp\\Command\\Command))
#18 E:\\Projektek\\xyz\\vendor\
estcord\
estcord\\src\\OverriddenGuzzleClient.php(86): GuzzleHttp\\Command\\ServiceClient->__call('leaveGuild', Array)
#19 E:\\Projektek\\xyz\\app\\Http\\Controllers\\ApiController.php(1402): RestCord\\OverriddenGuzzleClient->__call('leaveGuild', Array)
#20 [internal function]: App\\Http\\Controllers\\ApiController->myservers_delete(Object(Illuminate\\Http\\Request))
#21 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): call_user_func_array(Array, Array)
#22 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('myservers_delet...', Array)
#23 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\ApiController), 'myservers_delet...')
#24 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(176): Illuminate\\Routing\\Route->runController()
#25 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(681): Illuminate\\Routing\\Route->run()
#26 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\ThrottleRequests.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 60, '1')
#31 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Middleware\\Authenticate.php(43): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'api')
#33 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#35 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#36 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#37 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#38 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#39 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#40 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 E:\\Projektek\\xyz\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#52 E:\\Projektek\\xyz\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#53 E:\\Projektek\\xyz\\public\\index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#54 {main}
"} `
Hmm now I think back two months ago I had the php 7.2. Hmm maybe I need to expand something in the php settings?
Hmm I don't know. I will try to setup stuffs in the php.ini file.

**Comment by brandinarsenault** [comment]
Experiencing this issue on 7.3 as well, unable to find the resolution yet but will update if I find anything.

**Comment by cryptiklemur** [comment]
You can catch the actual error from discord with:

```php
try {
    $discordguild = new DiscordClient( [ 'token' => env( 'DISCORD_BOT_TOKEN' ) ] );
    $discordguild->user->leaveGuild(['guild.id' => (int)$guildid]);
} (\GuzzleHttp\Exception\ClientException $e) {
    var_dump($e->getResponse()->getBody()->getContents()); // May need to toString this as well
}
```

**Comment by alejandrojsn** [comment]
I'm having this same problem, when I get the error it only says: 400 Bad Request and code 0. But doing doing the same request with curl works fine

**Comment by alejandrojsn** [comment]
I just discovered that if I add the header 'Content-Type'  => 'application/json', (which is present in the request made by Restcord) to my request using curl, it fails with the same error (400 Bad Request). Then, I removed the header from the request made by restcord and it worked.
Don't know if that's all the bug or there is more, but it should help
