### ISSUE TITLE
Issue with modifyGuildRolePositions

### ISSUE THREAD

**Issue by HilbertGilbertson** [restcord/restcord#11]
Perhaps I am doing something terribly wrong, but I am having no luck with modifyGuildRolePositions. It seems to return an array of guild roles, but does not change the position of the role.

My use example:
```php
$restcord->guild->modifyGuildRolePositions(['guild.id' => 90157169906819070, 'id' => 296755184212639744, 'position' => 4]);
```

The position of the role does not change (remains at 1) and the returned roles array correctly shows the position number (but has not changed it).

My script has been able to create the role and modify the role fine, but I am having no luck with changing its position.

**Comment by aequasi** [comment]
Should be resolved now
