### ISSUE TITLE
Problem with receiving members from guild.

### ISSUE THREAD

**Issue by s-kerdel** [restcord/restcord#110]
I've been trying your library to create a simple page but I am stuck at receiving the guild members.

Maybe something has changed since `$discord->guild->getGuild(['guild_id' => ID_HERE])` doesn't contain any members either. Is there a server setting avoiding this?

Another example is `$discord->guild->listGuildMembers(['guild.id' => ID_HERE])`, this doesn't return the full member list either, but instead only returns one - thus no permission error?

please let me know if you require more details.

**Comment by oliverschloebe** [comment]
The `members` and `members_count` fields are [only available within the `GUILD_CREATE?` event](https://discordapp.com/developers/docs/resources/guild#guild-object), not with calling `->getGuild()`.

The `->listGuildMembers()` method returns 1 member per default, [unless you provide a `limit` parameter](https://discordapp.com/developers/docs/resources/guild#list-guild-members) for up to 1000 members per call.

**Comment by s-kerdel** [comment]
I see now, thank you for helping me out.
Providing a limit gave me the expected result.

Since the documentation of restcord did note this, i'll look at the API documentation next time.
