### ISSUE TITLE
How to mention a specific role(s)?

### ISSUE THREAD

**Issue by pleinx** [restcord/restcord#111]
Can somebody please provide a example how to mention custom rules?
"@everyone" is working, but not my new created (yes, mentionable is active)

I found these line but no example in your docs:
https://github.com/restcord/restcord/blob/master/src/Model/Channel/Message.php#L131

**Comment by oliverschloebe** [comment]
In Discord in general you can mention people with `<@ID>` and mentionable roles with `<@&ID>`.

**Comment by pleinx** [comment]
Hats correct. But how it works in restcord?

I've tried:
```
$discord->channel->createMessage([
    'channel.id' => CHANNEL_ID,
    'content' => '@mycreatedrole Hello World',
]);
```

But it doesnt work. If i try the same via desktop client, it works well.

**Comment by oliverschloebe** [comment]
Try
```
$discord->channel->createMessage([
    'channel.id' => CHANNEL_ID,
    'content' => '<@&0123456789> Hello World',
]);
```
.. where `0123456789` is the ID of the mentionable role. Be sure to not omit the `<` and `>` parts.
