### ISSUE TITLE
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error

### ISSUE THREAD

**Issue by DevilLordAero** [restcord/restcord#113]
Got this error
```Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://discordapp.com/api/v6/channels/692749458353684622/messages` resulted in a `400 Bad Request` response: in /opt/lampp/htdocs/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113 Stack trace: #0 /opt/lampp/htdocs/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 /opt/lampp/htdocs/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 /opt/lampp/htdocs/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #3 /opt/lampp/htdocs/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #4 /opt/lampp/htdocs/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(118): GuzzleHttp\Promise\TaskQueue->run() #5 /opt/lam in /opt/lampp/htdocs/vendor/guzzlehttp/command/src/Exception/CommandException.php on line 57```

```php
<?php
include __DIR__.'/vendor/autoload.php';

use RestCord\DiscordClient;

$discord = new DiscordClient(['token' => 'tokenhere']); // Token is required
$discord->channel->createMessage([
    'channel.id' => 692749458353684622,
    'content' => "New !",
    'embed' => [
        "title"=>"New Contribution by " . $_SESSION['name'],
        "fields" => [
            [
                "name" => "Card ID",
                "value" => $_SESSION['cardID']
            ],
            [
                "name" => "Idol Name",
                "value" => $_SESSION['idolName']
            ],
            [
                "name" => "Rarity",
                "value" => $_SESSION['rarity']
            ],
            [
                "name" => "Card Type",
                "value" => $_SESSION['cardType']
            ],
            [
                "name" => "smile",
                "value" => $_SESSION['smile']
            ],
            [
                "name" => "Pure",
                "value" => $_SESSION['pure']
            ],
            [
                "name" => "Cool",
                "value" => $_SESSION['cool']
            ],
            [
                "name" => "Year",
                "value" => $_SESSION['year']
            ],
            [
                "name" => "Unit",
                "value" => $_SESSION['unit']
            ],
            [
                "name" => "Sub Unit",
                "value" => $_SESSION['subunit']
            ]
        ]
    ]
]);
?>
```

**Comment by oliverschloebe** [comment]
Have you run this before once? https://github.com/restcord/restcord/blob/master/extra/gateway.html

**Comment by DevilLordAero** [comment]
> Have you run this before once? https://github.com/restcord/restcord/blob/master/extra/gateway.html

i think embed have problem., it can work fine without embed

**Comment by oliverschloebe** [comment]
> > Have you run this before once? https://github.com/restcord/restcord/blob/master/extra/gateway.html
> 
> i think embed have problem., it can work fine without embed

Try https://rawcdn.githack.com/restcord/restcord/c3b2810ab8b0029761e7ea7ab442f6157299e74f/extra/gateway.html

**Comment by alboltdrogo** [comment]
I'm having the same issue when using embedded fields. Without using the embedded fields it works fine. Gateway is definitely not the problem

**Comment by oliverschloebe** [comment]
> I'm having the same issue when using embedded fields. Without using the embedded fields it works fine. Gateway is definitely not the problem

AFAIK there's a limit on how many embedded fields you can add. Maybe you ran into that limit.

**Comment by alboltdrogo** [comment]
My bad, this issue was on my end, I was passing a single array instead of an array of arrays. Works perfectly :)
