### ISSUE TITLE
symfony/options-resolver any chance of v 5 support?

### ISSUE THREAD

**Issue by benzon** [restcord/restcord#117]
Just wondering will it work with symfony/options-resolver 5 and higher?

**Comment by bkuhl** [comment]
The composer.json files [indicates it works with v5](https://github.com/restcord/restcord/blob/master/composer.json#L11), but may work with later versions as well.  A great way to contribute would be to fork the project and try it out on later versions.

**Comment by cryptiklemur** [comment]
Yes, it does work with ^5.1
