### ISSUE TITLE
'Validation errors: [channel.id] must be of type integer

### ISSUE THREAD

**Issue by Jon-LH-Hart** [restcord/restcord#12]
I get an uncaught guzzle exception with this message when trying to run the example message. Using my own bot token and channel id of course. Any idea what I could be doing wrong? 

```
$discord = new DiscordClient(['token' => 'my bot token']); // Token is required

var_dump($discord->channel->createMessage(['channel.id' => 294267349572255744, 'content' => 'Foo Bar Baz']));
```

Here is the stack trace that is presented. 

Fatal error: Uncaught exception 'GuzzleHttp\Command\Exception\CommandException' with message 'Validation errors: [channel.id] must be of type integer' in C:\xampp\htdocs\restcord\vendor\guzzlehttp\guzzle-services\src\Handler\ValidatedDescriptionHandler.php:75 Stack trace: #0 C:\xampp\htdocs\restcord\vendor\guzzlehttp\command\src\ServiceClient.php(85): GuzzleHttp\Command\Guzzle\Handler\ValidatedDescriptionHandler->GuzzleHttp\Command\Guzzle\Handler\{closure}(Object(GuzzleHttp\Command\Command)) #1 C:\xampp\htdocs\restcord\vendor\guzzlehttp\command\src\ServiceClient.php(77): GuzzleHttp\Command\ServiceClient->executeAsync(Object(GuzzleHttp\Command\Command)) #2 C:\xampp\htdocs\restcord\vendor\guzzlehttp\command\src\ServiceClient.php(153): GuzzleHttp\Command\ServiceClient->execute(Object(GuzzleHttp\Command\Command)) #3 C:\xampp\htdocs\restcord\main_controller.php(40): GuzzleHttp\Command\ServiceClient->__call('createMessage', Array) #4 C:\xampp\htdocs\restcord\main_controller.php(40): GuzzleHttp\Command\Guzzle\GuzzleClient->creat in C:\xampp\htdocs\restcord\vendor\guzzlehttp\guzzle-services\src\Handler\ValidatedDescriptionHandler.php on line 75

**Comment by aequasi** [comment]
What version of PHP are you running on? and arch

**Comment by aequasi** [comment]
What version of PHP are you running on? and arch

**Comment by mzmarkib** [comment]
@aequasi I am using xampp for running the php server. It is the latest version of xammp. I even tried it on the PHP ver 7.1

**Comment by aequasi** [comment]
what architecture? 32bit? 64bit?

**Comment by mzmarkib** [comment]
@aequasi 64bit

**Comment by mzmarkib** [comment]
@aequasi 32-bit [on-windows], is the problem? I even tried hosting it on a web-server (meaning, I bought a hosting package and hosted it there)

**Comment by aequasi** [comment]
You need to be running on 64 bit PHP

**Comment by M4sterZer0** [comment]
Same problem. Webhosting. Can you fix it @aequasi ?

**Comment by aequasi** [comment]
32 bit support will not be added. There are plenty of hosts that support 64 bit PHP. Digital Ocean droplets can be hosted as cheap as $5 a month.
