### ISSUE TITLE
Validation errors: [avatar] must be of type avatar data

### ISSUE THREAD

**Issue by brqt** [restcord/restcord#121]
Got an error about validation when modifying user avatar:
```
$data = [
  'username' => $username, // type string
  'avatar'   => 'data:image/jpeg;base64,base64_data_of_image' // type string
];
$discord->user->modifyCurrentUser($data);
```
Error Message:
![alt text](https://i.imgur.com/5PLGqbH.png "Error Message")

---

I found the problem in : `function updateParameterTypes(array &$parameterConfig)  line:371 file:DiscordClient.php`
So I had to add this code to make it work properly

```
if (in_array($parameterConfig['type'], ['avatar data', 'avatar data string'])) {
    $parameterConfig['type'] = 'string';
}
```

Thanks for this awesome library ❤

**Comment by bkuhl** [comment]
Thanks for taking the time to post here.  I ran into the same issue today and this saved me some time tracking down what was going on.  I've created a PR for the solution.
