### ISSUE TITLE
AbstractRateLimitProvider getRoute including non major parameters

### ISSUE THREAD

**Issue by bumbummen99** [restcord/restcord#122]
The routes for the RateLimiter include non major parameters, this is provoking rate limit Exceptions if not handled externally.

From the discord api docs:
> Additionally, rate limits take into account major parameters in the URL. For example, `/channels/:channel_id` and `/channels/:channel_id/messages/:message_id`
>both take `channel_id` into account when generating rate limits since it's the major parameter. Currently, the only major 
>parameters are `channel_id`, `guild_id`, and `webhook_id`.

[Source](https://discord.com/developers/docs/topics/rate-limits#more-precise-rate-limit-resets)

**Comment by bumbummen99** [comment]
Relates #53

**Comment by bumbummen99** [comment]
Interesting: https://github.com/discord/discord-api-docs/issues/1551#issuecomment-620550841

**Comment by aequasi** [comment]
Mind making a PR for this? Otherwise it'll be a few days before i can get to this

**Comment by bumbummen99** [comment]
I was on it thought i did not yet come up with an elegant solution to determine what command has been called in the middleware or getting access to its definition from the JSON. Also i am not quite sure if it is possible to precompute the bucket id so i think the easiest solution would be to:
* create a hash of the tempalate url + major parameters appended
* hash the final url with minor parameters stripped

And use the result as the index instead of the final url.

Only thing i am really uncertain of are the rate limits on the different methods since they can share their bucket / rate limit but to me it is not clear when they do so. It is mentioned that DELETE & POST *could* share a limit but not when.
