### ISSUE TITLE
Cannot be disable Guzzle HTTP errors

### ISSUE THREAD

**Issue by TheAndrey** [restcord/restcord#124]
I want to disable exceptions when API returns a error. I found hidden option `httpErrors`, but validation not allow to use it. Parameter `guzzleOptions` doesn't work, because it will overridden with defaults (Why not opposite?).
* https://github.com/restcord/restcord/blob/master/src/DiscordClient.php#L100-L110
* https://github.com/restcord/restcord/blob/master/src/DiscordClient.php#L138

**Comment by aequasi** [comment]
Not sure tbh. Wrote that logic so long ago. If you PR a change, I can look at adding that in

**Comment by TheAndrey** [comment]
Created: https://github.com/restcord/restcord/pull/125

**Comment by aequasi** [comment]
Thanks!
