### ISSUE TITLE
retrieving error {"message": "401: Unauthorized", "code": 0}

### ISSUE THREAD

**Issue by Blackpaul** [restcord/restcord#129]
hello,

anybody know's how to solve this problem?
when i try to get my channel, im getting this error 401.
sorry im newbie, sorry for my english.
any comment's are very much appreciated.
here is my codes, also from restcord sample.

	error_reporting(E_ALL & ~E_NOTICE);
	@ini_set('display_errors', 1);

	include __DIR__.'/vendor/autoload.php';

	$discord = new \RestCord\DiscordClient([
        'token' => 'J70Aw2Z17t_RrrA9rnWBMcnDy2eNN5h0wKVuIpZjQ771xazaNTnYH1HwrWKR9o8pzUdk'
    ]);

    $channel_messages = $discord->channel->getChannelMessages(['channel.id' => 752773585285677058, 'limit' => 3]);

	var_dump($channel_messages);

**Comment by oliverschloebe** [comment]
Try
```php
$client = new DiscordClient([
    'token' => 'NF6cZn9VjgPtISl98WfQHYjK0kD0te5xp7Yx3TjzUSKo8anKJ_9_IMlkO58zzQtgUZsy'
]);
```

**Comment by Blackpaul** [comment]
> Try
> 
> ```
> $client = new DiscordClient([
>     'token' => 'NF6cZn9VjgPtISl98WfQHYjK0kD0te5xp7Yx3TjzUSKo8anKJ_9_IMlkO58zzQtgUZsy'
> ]);
> ```

not working sir. still have err 500 with this code.

**Comment by oliverschloebe** [comment]
May you please post the entire error message? Thanks!

**Comment by Blackpaul** [comment]
> May you please post the entire error message? Thanks!

https://gyazo.com/cd333dd1d733c85c16a4437c26971321

and the code i've used

https://gyazo.com/b03251753065ddfaa7a6318bf4d6c64d

**Comment by oliverschloebe** [comment]
Please add the following to the beginning of the script:
```
@ini_set('display_errors', 1);
error_reporting(E_ALL & ~E_NOTICE);
```
which should be displaying the actual error message(s).

**Comment by Blackpaul** [comment]
> Please add the following to the beginning of the script:
> 
> ```
> error_reporting(E_ALL & ~E_NOTICE);
> @ini_set('display_errors', 1);
> ```
> 
> which should be displaying the actual error message(s).

thank you so much sir,
now, i've got this fatal err


Fatal error: Uncaught InvalidArgumentException: No operation found named GetChannel in /var/www/sites-eu/allkeyshop.com/admin/bot_de_v2/staging/discord/vendor/guzzlehttp/guzzle-services/src/GuzzleClient.php:72 Stack trace: #0 /var/www/sites-eu/allkeyshop.com/admin/bot_de_v2/staging/discord/vendor/guzzlehttp/command/src/ServiceClient.php(153): GuzzleHttp\Command\Guzzle\GuzzleClient->getCommand('GetChannel', Array) #1 /var/www/sites-eu/allkeyshop.com/admin/bot_de_v2/staging/discord/vendor/restcord/restcord/src/OverriddenGuzzleClient.php(86): GuzzleHttp\Command\ServiceClient->__call('getChannel', Array) #2 /var/www/sites-eu/allkeyshop.com/admin/bot_de_v2/staging/discord/message.php(13): RestCord\OverriddenGuzzleClient->__call('getChannel', Array) #3 {main} thrown in /var/www/sites-eu/allkeyshop.com/admin/bot_de_v2/staging/discord/vendor/guzzlehttp/guzzle-services/src/GuzzleClient.php on line 72

**Comment by oliverschloebe** [comment]
Still getting the same error when using my code from https://github.com/restcord/restcord/issues/129#issuecomment-689400413 ?

**Comment by Blackpaul** [comment]
> Still getting the same error when using my code from [#129 (comment)](https://github.com/restcord/restcord/issues/129#issuecomment-689400413) ?

yes sir
https://gyazo.com/2a3e7e5d312cc2e5706c3afb91b10622

and now i got fatal err

https://gyazo.com/d685c3e24ec96c5d6c8000947f187976

**Comment by aequasi** [comment]
`$client->guild->getChannel()` is not a real method. And you need to reset your token now. Next time, replace it

**Comment by Blackpaul** [comment]
> `$client->guild->getChannel()` is not a real method. And you need to reset your token now. Next time, replace it

thank you sir,
i change it now with 

$channel_messages = $discord->channel->getChannelMessages(['channel.id' => 752773585285677058, 'limit' => 3]);

but im getting this err 401 Unauthorized

how am i able to solve this? please help.

https://gyazo.com/0b5e4974eb90d015545876744d12d8ea

**Comment by aequasi** [comment]
Your user for that token doesn't have access to that channel. Thats what unauthorized means.
