### ISSUE TITLE
convertResponseToResult receives an object instead of array

### ISSUE THREAD

**Issue by sn0opy** [restcord/restcord#14]
I was creating a new DM via `$client->user->createDm(['recipient_id' => 123])`. Unfortunately this fails with the following error:

> Argument 1 passed to GuzzleHttp\Command\Result::__construct() must be of the type array, object given, called in vendor/restcord/restcord/src/DiscordClient.php on line 266 in vendor/guzzlehttp/command/src/Result.php on line 14

This can be fixed by casting `$data` to an array even though I'm not sure, what else it may break.

**Comment by aequasi** [comment]
Not going to cast. Would rather fix the underlying issue. Will check that out though.
