### ISSUE TITLE
removeGuildBan always gives 400 Bad Request

### ISSUE THREAD

**Issue by littleblue50** [restcord/restcord#140]
every time I use removeGuildBan I get a 400 Bad Request even though Ive confirmed the IDs used are correct.

from my logs I see:
```
There was an error executing the removeGuildBan command: Client error: `DELETE https://discordapp.com/api/guilds/<guild id>/bans/<user id>` resulted in a `400 Bad Request`
```

**Comment by florianfrictus** [comment]
I do have the same error I always get a 400 Bad Request but after checking the ID's they are correct and should remove the ban.
There is also se same error for createGuildBan.

```
GuzzleHttp\Command\Exception\CommandClientException
There was an error executing the removeGuildBan command: Client error: `DELETE https://discord.com/api/v6/guilds/<guild.id>/bans/<user.id>` resulted in a `400 Bad Request` response:
```

**Comment by aequasi** [comment]
If you catch the Guzzle exception, you can print out the body to get the actual error from Discord.
