### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by SeinopSys** [restcord/restcord#142]
PHP version 8 came out recently and I did not see any issues tracking support for it yet so I figured I would create one. The current version constraint prevents me from upgrading my application to it, so I would definitely appreciate if compatibility could be checked and the constraint could be updated accordingly.

**Comment by aequasi** [comment]
PRs are welcome

**Comment by nssmart** [comment]
Not directly related, but close, I guess.
Are there any reasons to lock guzzlehttp/guzzle under 7.0?
Becomes incompatible with packages requiring guzzle >= 7.0.

**Comment by aequasi** [comment]
The specific reason
