### ISSUE TITLE
Validation errors: [before] must be of type integer [after] must be of type integer

### ISSUE THREAD

**Issue by bkuhl** [restcord/restcord#15]
According to https://discordapp.com/developers/docs/resources/user#get-current-user-guilds these attributes are optional.  However, not supplying them throws this exception:

```
CommandException in ValidatedDescriptionHandler.php line 75:
Validation errors: [before] must be of type integer
[after] must be of type integer
```

If they're required, this method should really accept multiple parameters rather than accepting an array.

**Comment by aequasi** [comment]
Should be resolved now
