### ISSUE TITLE
Uncaught Exception: {"message": "400: Bad Request", "code": 0} - How to use the gateway?

### ISSUE THREAD

**Issue by JDittmerCOM** [restcord/restcord#155]
Hi, when I want to ban someone, I always get the same error message.
I've already read that you should somehow use this gateway, but I have no idea how to use it with me?
Can you help me with this? 

**Code**
```php
public function banUser($userId, $reason = ""){
	$dc = new DiscordClient(['token' => DISCORDBOT_TOKEN]);
	$dc->gateway->getGatewayBot();
	$dc->guild->createGuildBan(['guild.id' => DISCORD_GUILDID, 'user.id' => (int)$userId, 'reason?' => $reason]);
}
```

**Error**
`
Fatal error: Uncaught Exception: {"message": "400: Bad Request", "code": 0} in T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\restcord\restcord\src\DiscordClient.php:214 Stack trace: #0 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\restcord\restcord\src\DiscordClient.php(188): RestCord\DiscordClient->convertResponseToResult('guild', Array, Object(GuzzleHttp\Psr7\Response), Object(GuzzleHttp\Command\Command)) #1 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\command\src\ServiceClient.php(215): RestCord\DiscordClient->RestCord\{closure}(Object(GuzzleHttp\Psr7\Response), Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Command\Command)) #2 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\command\src\ServiceClient.php(177): GuzzleHttp\Command\ServiceClient->transformResponseToResult(Object(GuzzleHttp\Psr7\Response), Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Command\Command)) #3 [internal function]: GuzzleHttp\Command\ServiceClient->GuzzleHttp\Command\{closure}() #4 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\promises\src\Coroutine.php(140): Generator->send(Object(GuzzleHttp\Psr7\Response)) #5 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\promises\src\Promise.php(204): GuzzleHttp\Promise\Coroutine->_handleSuccess(Object(GuzzleHttp\Psr7\Response)) #6 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\promises\src\Promise.php(153): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL) #7 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\promises\src\TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #8 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php(118): GuzzleHttp\Promise\TaskQueue->run() #9 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php(145): GuzzleHttp\Handler\CurlMultiHandler->tick() #10 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\promises\src\Promise.php(248): GuzzleHttp\Handler\CurlMultiHandler->execute(true) #11 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\promises\src\Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn() #12 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\promises\src\Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending() #13 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\promises\src\Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList() #14 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\promises\src\Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #15 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\promises\src\Coroutine.php(67): GuzzleHttp\Promise\Promise->wait() #16 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\promises\src\Promise.php(248): GuzzleHttp\Promise\Coroutine->GuzzleHttp\Promise\{closure}(true) #17 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\promises\src\Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn() #18 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\promises\src\Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #19 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\promises\src\Coroutine.php(103): GuzzleHttp\Promise\Promise->wait(true) #20 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\command\src\ServiceClient.php(77): GuzzleHttp\Promise\Coroutine->wait() #21 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\command\src\ServiceClient.php(153): GuzzleHttp\Command\ServiceClient->execute(Object(GuzzleHttp\Command\Command)) #22 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\restcord\restcord\src\OverriddenGuzzleClient.php(86): GuzzleHttp\Command\ServiceClient->__call('createGuildBan', Array) #23 T:\_WEB\htdocs\MissionV-Main\resources\classes\discord.php(27): RestCord\OverriddenGuzzleClient->__call('createGuildBan', Array) #24 T:\_WEB\htdocs\MissionV-Main\resources\ajax-php\acp-account.php(643): discord->banUser('788118584294375...', 'TEST') #25 {main} Next GuzzleHttp\Command\Exception\CommandException: There was an error executing the createGuildBan command: {"message": "400: Bad Request", "code": 0} in T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\command\src\Exception\CommandException.php:57 Stack trace: #0 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\command\src\ServiceClient.php(179): GuzzleHttp\Command\Exception\CommandException::fromPrevious(Object(GuzzleHttp\Command\Command), Object(Exception)) #1 [internal function]: GuzzleHttp\Command\ServiceClient->GuzzleHttp\Command\{closure}() #2 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\promises\src\Coroutine.php(140): Generator->send(Object(GuzzleHttp\Psr7\Response)) #3 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\promises\src\Promise.php(204): GuzzleHttp\Promise\Coroutine->_handleSuccess(Object(GuzzleHttp\Psr7\Response)) #4 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\promises\src\Promise.php(153): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL) #5 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\promises\src\TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #6 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php(118): GuzzleHttp\Promise\TaskQueue->run() #7 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php(145): GuzzleHttp\Handler\CurlMultiHandler->tick() #8 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\promises\src\Promise.php(248): GuzzleHttp\Handler\CurlMultiHandler->execute(true) #9 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\promises\src\Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn() #10 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\promises\src\Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending() #11 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\promises\src\Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList() #12 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\promises\src\Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #13 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\promises\src\Coroutine.php(67): GuzzleHttp\Promise\Promise->wait() #14 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\promises\src\Promise.php(248): GuzzleHttp\Promise\Coroutine->GuzzleHttp\Promise\{closure}(true) #15 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\promises\src\Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn() #16 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\promises\src\Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #17 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\promises\src\Coroutine.php(103): GuzzleHttp\Promise\Promise->wait(true) #18 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\command\src\ServiceClient.php(77): GuzzleHttp\Promise\Coroutine->wait() #19 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\command\src\ServiceClient.php(153): GuzzleHttp\Command\ServiceClient->execute(Object(GuzzleHttp\Command\Command)) #20 T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\restcord\restcord\src\OverriddenGuzzleClient.php(86): GuzzleHttp\Command\ServiceClient->__call('createGuildBan', Array) #21 T:\_WEB\htdocs\MissionV-Main\resources\classes\discord.php(27): RestCord\OverriddenGuzzleClient->__call('createGuildBan', Array) #22 T:\_WEB\htdocs\MissionV-Main\resources\ajax-php\acp-account.php(643): discord->banUser('788118584294375...', 'TEST') #23 {main} thrown in T:\_WEB\htdocs\MissionV-Main\resources\rest-discord\vendor\guzzlehttp\command\src\Exception\CommandException.php on line 57
`

**Comment by cryptiklemur** [comment]
You dont need the gateway stuff 

```php
public function banUser($userId, $reason = ""){
	$dc = new DiscordClient(['token' => DISCORDBOT_TOKEN]);
        $options = ['guild.id' => (int) DISCORD_GUILDID, 'user.id' => (int) $userId];
        if (!empty($reason)) {
            $options['reason'] = $reason;
        }

	$dc->guild->createGuildBan($options);
}
```

**Comment by JDittmerCOM** [comment]
In principle it is exactly the same as what I already have, only without the getGatewayBot.
Unfortunately, that doesn't solve my problem.

**Comment by cryptiklemur** [comment]
It is not the same in principle, the options array isn't the same as what you had

**Comment by JDittmerCOM** [comment]
The only change is that you have added (int) to the Discord Guildid and you have $reason separated.
In the end, however, it produced the exact same mistake.

**Comment by cryptiklemur** [comment]
you had `reason?` as the key, which is not the same. `reason?` as a key would definitely produce a 400 error. 

You can catch the Guzzle error from the call, and log out the response body so it'll tell you exactly what went wrong

**Comment by JDittmerCOM** [comment]
Okay, and how can I execute the error output in my code with Guzzle or what should the catch be called exactly?

**Comment by cryptiklemur** [comment]
i forget which exception it is, but $e->getResponse()->getBody()->__toString()

**Comment by JDittmerCOM** [comment]
I currently have it as a test, but there are no extra messages at all. 

```php
public function banUser($userId, $reason = ""){
	$dc = new DiscordClient(['token' => DISCORDBOT_TOKEN]);
	$options = ['guild.id' => (int) DISCORD_GUILDID, 'user.id' => (int) $userId];
	if (!empty($reason)) {
		$options['reason'] = $reason;
	}

	try {
		$dc->guild->createGuildBan($options);
	} catch (GuzzleHttp\Exception\ClientException $e) {
		var_dump($e->getResponse()->getBody()->__toString());
	}
}
```

**Comment by cryptiklemur** [comment]
Im not entirely sure tbh. I dont have a way to debug this right now, but the response body should have the information on why its a bad request

**Comment by JDittmerCOM** [comment]
Because I simply need such functions, but they should also work for me, which has so far worked with other functions without any problems.
If you don't seem to have a clue, then don't understand the error, why it arises.

**Comment by cryptiklemur** [comment]
I don't, sorry. Like i said, the response body should have the information on why its throwing a 400

**Comment by JDittmerCOM** [comment]
Hmm okay
Not that great, of course.
Then I have to think of something else for it. Nevertheless, thanks for the feedback.
