### ISSUE TITLE
listGuildMembers returns a 403 FORBIDDEN error?

### ISSUE THREAD

**Issue by RobertGrubb** [restcord/restcord#157]
Hey there,

It's possible I've just been looking at this too long, however, I'm using the syntax below with the parameters:

```
$client->listGuildMembers([
        'guild.id' => intval($guildId),
        'limit' => intval($limit)
      ]);
```

And I have used oauth to grant the correct permissions that include managing members, etc. However, I'm always getting a 403 in return. When looking at my bot integration on the server itself, it has the manage members checked along with every other permission (lol). 

Any ideas? I've been looking this for way too long I guess.

**Comment by oliverschloebe** [comment]
What's the value of `$limit`? Can't be >1000

**Comment by RobertGrubb** [comment]
@oliverschloebe Hey there!

The value of limit has been everything under the sun... 1, 10, 25, 50, 100 etc - All the same outcome.

**Comment by RobertGrubb** [comment]
Figured this out, it was my fault, nothing to do with the communication from the api. Ended up that I looked over enabling intent.
