### ISSUE TITLE
Support for discord Scheduled Events

### ISSUE THREAD

**Issue by PenguinNexus** [restcord/restcord#165]
Please add support for discord scheduled events

**Comment by HuckinB** [comment]
This would be a great addition 🙏

**Comment by LeigerGaming** [comment]
There is a pull request from someone for this in #166 by @PenguinNexus here - but it seems that it was already partially implemented in the v9 branch.

The partial implementation in v9 branch looks like it has issues though, so my suggested fixes are in #174. If that gets fixed, it should mean we can create scheduled events :) I have successfully created and listed events on my Discord server using the code in that pull request.

**Comment by PenguinNexus** [comment]
Thank you so much for being able to test for me, very short of time at the moment!

**Comment by LeigerGaming** [comment]
I haven't tested your specific changes because the repository maintainer pointed out that Restcord already has code for handling Guild Scheduled Events.

That code also wasn't fully functional yet though.

**Comment by PenguinNexus** [comment]
Closing as this project seems to have been abandoned.
