### ISSUE TITLE
500 Server error?

### ISSUE THREAD

**Issue by venneflyZ** [restcord/restcord#18]
What's wrong here? I just get HTTP error 500...
I'm sure it's not my code, because if I swap out createChannelInvite with getChannelInvites it works just fine...

```
use RestCord\DiscordClient;
  include __DIR__.'/vendor/autoload.php';
  $authToken = 'REMOVED';
  $channel = 'ALSO REMOVED';    // There would be an int here normally, but I removed it for GitHub.

  $discord = new DiscordClient(['token' => $authToken]);
  var_dump($discord->channel->createChannelInvite(['channel.id' => $channel]));
```

**Comment by f0nt4** [comment]
Try:
```php
var_dump($this->discord->channel->createChannelInvite(['channel.id' => (int)$channel]));
```
I've tried it here, and all works fine!
The response I got was:
```json
{"channel":{"type":0,"id":"335438691872332520","name":"testchannel"},"code":"pTYhp9","guild":{"splash":null,"id":"126371503520647080","icon":"8964b6635235heyrgta0af3b804h6ooc","name":"Server Name"}}
```

**Comment by aequasi** [comment]
Woah, totally didnt even see this issue... Yeah, make sure you are on the latest. You can also try to catch the exception, and get the message from it.

**Comment by mhaque02** [comment]
On 0.1.4 and getting the same error. The invite code is generated on the server but on page reload it says

>  [2/2] CommandException: There was an error executing the createChannelInvite command: No model found named Channel\Invite  +

**Comment by aequasi** [comment]
This should be fixed in develop now
