### ISSUE TITLE
Is it possible to send private message to a guild member ?

### ISSUE THREAD

**Issue by AlexPietri** [restcord/restcord#183]
Hello, 
Is it possible to send private message to a guild member ? 
I 've saw that it exist the createDm method but I don't know if is it for that and if it does, what correspond recipient_id ?

**Comment by mkshb** [comment]
Hi AlexPietri,

to send private messages you first need to create a for this. That's what createDm does (see https://discord.com/developers/docs/resources/user#create-dm) . After this you can send messages to this channel. 

Regards

**Comment by AlexPietri** [comment]
> Hi AlexPietri,
> 
> to send private messages you first need to create a for this. That's what createDm does (see https://discord.com/developers/docs/resources/user#create-dm) . After this you can send messages to this channel.
> 
> Regards

Ok, so I've tried this method with the user id and get error 400 then i've tried with the username and the discriminator (username#discriminator). In the second test it return nothing. So i don't know what i have to do next. 
Sorry i'm new in creating bot discord. 
Can you help me ? 
Thanks for your help.

**Comment by AlexPietri** [comment]
My bad i was using the wrong token --"
