### ISSUE TITLE
1.0.0 Release

### ISSUE THREAD

**Issue by aequasi** [restcord/restcord#2]
Need the following things before a 1.0.0 release

* [x] Rate Limit Handling (429 and Pre-Ratelimit)
* [x] Logging
* [x] Support for all REST endpoints
* [x] Testing of some sort. This will be difficult. Need to mock endpoints.
* [x] Support different token types (No token, Bot Token, OAuth Token, User Token)
* [x] Intellisense Helpers (Dummy classes, probably)
* [x] Response Validation Models
* [x] Examples
* [x] Make sure everything works.

**Comment by f0nt4** [comment]
Here's a pastebin of the controller which I created in Laravel. You might be able to use this for examples.
https://pastebin.com/FWv6M0DG
