### ISSUE TITLE
Must be of type int

### ISSUE THREAD

**Issue by f0nt4** [restcord/restcord#20]
Hi aequasi,

I'm trying to use this package in Laravel. All is going well. The only thing I needed to do is require it and after that I was able to use it.

There's one thing though that I'm finding a little bit annoying.
I have my bot.key and guild.id in my .env file and I'd like to use it like this:

```php
$info = $discord->guild->getGuild(['guild.id' => env('DISCORD_GUILD')]);
```
But then it will throw an exception because its an string. I would have to put (int) in front of env() everytime I would use something from the .env file or when I'm using a user's discord.id from the database.
Another form of validation would be highly appreciated!

**Comment by aequasi** [comment]
I have no plans to add other forms of validation, as it adds more work to the core logic that I'm purposefully avoiding. 

My suggestion, would be to normalize your environmental variables at the start, and have them available when using the environment variables. You should also be storing your ids in the database as unsigned bigints anyways

**Comment by f0nt4** [comment]
Yeah, those id's in the db shouldn't be too much of a problem.
Any idea on how to handle input received from an url get or post request?
like this?
```php
public function user(Request $request)
	{
		$id = $request->get('id');

		// Information of the user on our server
		$userServer = $this->discord->guild->getGuildMember(['guild.id'=> (int)env('DISCORD_GUILD'), 'user.id' => (int)$id]);

		// Information of the user on Discord
		$userDiscord = $this->discord->user->getUser(['user.id' => (int)$id]);

		$result['userServer'] = $userServer;
		$result['userDiscord'] = $userDiscord;

		return response()->json($result);
	}
```

Oh, another question, did you by chance create something to easily get the user's avatar url from the cdn to be used in img tags? Something like this might do the trick:
http://i.imgur.com/wtmkx6K.png
Because then we might be able to do something like:
```php
$avatarUrl = $discord->user->getAvatarUrl(['user.id' => (int)$id]);
```

**Comment by aequasi** [comment]
You can cast it to an int at the start. I'm not super familiar with Laravel (Symfony guy myself). You might be able to use [Symfony's Option Resolver](http://symfony.com/doc/current/components/options_resolver.html) component to normalize the request. As for route params, you should be able to typehint those as ints, if you are on php7.

The avatar thing is something I could look at doing

**Comment by f0nt4** [comment]
Haha, not on php7 yet. Our forum can't handle that yet I believe.
I'm using the construct function now to define the guild.id as an integer.
So I can use $this->guildID in stead of the .env variable.

I've also created a function now to response with the url or the img tags of the avatar. It's not a lot of code, but would be a nice to have in this package.
```php
	/**
	* Get avatar of the user
	*
	* @param id of the user
	* @param 2nd param is url/img or nothing to default to json
	*
	* @return type url 	returns just the user's avatar url
	* @return type img 	returns html code to show the avatar
	* @return type json returns the url in an json encoded array
	*/
	public function getAvatar(Request $request)
	{
		$id = $request->get('id');
		$type = $request->get('type');

		$user = $this->discord->user->getUser(['user.id' => (int)$id]);
		$url = 'https://cdn.discordapp.com/avatars/'.$id.'/'.$user->avatar.'.webp';

		if ($type == 'url') {
			return $url;
		} elseif ($type == 'img') {
			return '<img src="'.$url.'" alt="'.$user->username.'\'s Avatar">';
		}
		$result = [
			'status' => 'OK',
			'data' => $url
		];
		return response()->json($result);
	}
```

**Comment by aequasi** [comment]
Mind making a suggestion issue for the avatar url

**Comment by f0nt4** [comment]
Nope, not a problem!
https://github.com/restcord/restcord/issues/21
