### ISSUE TITLE
Can we get a new release?

### ISSUE THREAD

**Issue by enygma** [restcord/restcord#25]
Hey - I know in #2 you're looking for a v1.0.0 release but it seems like there's a lot that has made it into `master` since the previous release in February. Would it be possible to get an updated release made for the changes? (like a v0.1.5)

**Comment by aequasi** [comment]
You *can* use dev-develop. This is the most up to date. I havent had a lot of time to test everything the last few months. Might be able to this weekend.

**Comment by enygma** [comment]
Well, I'm happy to help out with testing if there's a specific list of things to go over. I've been using some parts of the library on the `dev-develop` for a bit and they seem to be cooperating.

**Comment by aequasi** [comment]
I pushed a new release, and made a bunch of changes to develop

**Comment by enygma** [comment]
@aequasi excellent - thanks!
