### ISSUE TITLE
message delete requests not properly rate limited

### ISSUE THREAD

**Issue by brookgagnon** [restcord/restcord#31]
Looks like RateLimitProvider.php keeps track of different rate limits as follows:

`$route = $request->getMethod() .'-'.$request->getUri();`

So those requests with the same $route as specified, are considered as the same rate limit. (Hopefully I've got this right.)

Deleting different messages, however, have different routes, but are considered by discord as the same rate limit. Deleting a bunch of messages exceeds the rate limiter because delay is never triggered when it needs to be.

**Comment by sniper7kills** [comment]
This is my current hack for this:

Added the following to: RateLimitProvider.php
```
    private function getRoute(RequestInterface $request)
    {
        if($request->getMethod() == "DELETE")
            $URI = substr($request->getUri(), 0, strpos($request->getUri(), "/messages/"));
        else
            $URI = $request->getUri();
            
        return $request->getMethod().'-'.$URI;
    }
```
and replaced 
`$route = $request->getMethod().'-'.$request->getUri();` 
with 
`$route = $this->getRoute($request);`

As long as you are only deleting messages from a single channel it should work fine... But by no means an end-all solution.

**Comment by brookgagnon** [comment]
Thanks for this :). I've got a similar hack actually, I just do $route = $request->getMethod(); instead (dropping the getUri). It loses a bunch of specificity with potential performance decrease, but it works well for our purposes which is just to get and delete old messages.

**Comment by aequasi** [comment]
Resolved by https://github.com/restcord/restcord/commit/126e997de051f5fecf05ad94d767bded9e2404c9
