### ISSUE TITLE
getGuildChannels() misses a model

### ISSUE THREAD

**Issue by footychat** [restcord/restcord#4]
Two exceptions are thrown when using the getGuildChannels() method:

> InvalidArgumentException in Description.php line 163:
> No model found named Guild\Channel
> (in /var/www/html/vendor/guzzlehttp/guzzle-services/src/Description.php line 163)

And

> CommandException in CommandException.php line 57:
> There was an error executing the getGuildChannels command: No model found named Guild\Channel
> (in /var/www/html/vendor/guzzlehttp/command/src/Exception/CommandException.php line 57)

**Comment by aequasi** [comment]
Fixed by 8ac49da
