### ISSUE TITLE
Validation errors: [limit] must be of type integer [after] must be of type integer

### ISSUE THREAD

**Issue by edvardpotter** [restcord/restcord#41]
I get an exception when trying to get a list of guild users.
My code:

    $guild_id = my_id;
    $client = new DiscordClient(['token' => 'my_token']);
    var_dump($client->guild->listGuildMembers(['guild.id' => $guild_id]));

The documentation [says](https://discordapp.com/developers/docs/resources/guild#list-guild-members): 

> All parameters to this endpoint were optional

Throws an exception:

> Fatal error: Uncaught GuzzleHttp\Command\Exception\CommandException: Validation errors: [limit] must be of type integer [after] must be of type integer in E:\OSPanel\domains\discordapp\vendor\guzzlehttp\guzzle-services\src\Handler\ValidatedDescriptionHandler.php:76 Stack trace: #0 E:\OSPanel\domains\discordapp\vendor\guzzlehttp\command\src\ServiceClient.php(85): GuzzleHttp\Command\Guzzle\Handler\ValidatedDescriptionHandler->GuzzleHttp\Command\Guzzle\Handler\{closure}(Object(GuzzleHttp\Command\Command)) #1 E:\OSPanel\domains\discordapp\vendor\guzzlehttp\command\src\ServiceClient.php(77): GuzzleHttp\Command\ServiceClient->executeAsync(Object(GuzzleHttp\Command\Command)) #2 E:\OSPanel\domains\discordapp\vendor\guzzlehttp\command\src\ServiceClient.php(153): GuzzleHttp\Command\ServiceClient->execute(Object(GuzzleHttp\Command\Command)) #3 E:\OSPanel\domains\discordapp\index.php(14): GuzzleHttp\Command\ServiceClient->__call('listGuildMember...', Array) #4 {main} thrown in E:\OSPanel\domains\discordapp\vendor\guzzlehttp\guzzle-services\src\Handler\ValidatedDescriptionHandler.php on line 76

**Comment by janvernieuwe** [comment]
This has been fixed in the develop branch afaik.

**Comment by aequasi** [comment]
Fixed in master now
