### ISSUE TITLE
Unable to use with Laravel 5.6

### ISSUE THREAD

**Issue by keesh7663** [restcord/restcord#44]
Hello, I recently found the Laravel wrapper for restcord and decided to give the lib a spin.  Well, since the Laravel wrapper requires restcord I figure this is probably the more appropriate place to put this.

When attempting to install restcord on Laravel 5.6, it fails to install since Laravel 5.6 uses v 4.0.4 of symfony/options-resolver and I have no way of rolling this back without breaking my entire install.

So my question is are there plans on updating restcord to function with v 4.0.4 of symfony/options-resolver?  The Laravel wrapper is exactly what I've been looking for and would really like to use it but am at a standstill at the moment.

But anyways, here's the error message, just for good measure:
```
sudo composer require restcord/restcord:dev-master
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

 Problem 1
    - Installation request for restcord/restcord dev-master -> satisfiable by restcord/restcord[dev-master].
    - Conclusion: remove symfony/options-resolver v4.0.4
    - Conclusion: don't install symfony/options-resolver v4.0.4
    - restcord/restcord dev-master requires symfony/options-resolver >=2.6,<=4.0 -> satisfiable by symfony/options-resolver[v2.6.0, v2.6.1, v2.6.10, <Intermediate versions removed for brevity>, v3.4.2, v3.4.3, v3.4.4, v4.0.0].
    - Can only install one of: symfony/options-resolver[v2.6.0, v4.0.4].
    <Intermediate versions removed for brevity>
    - Can only install one of: symfony/options-resolver[v3.1.8, v4.0.4].
    - Can only install one of: symfony/options-resolver[v3.1.9, v4.0.4].
    - Installation request for symfony/options-resolver == 4.0.4.0 -> satisfiable by symfony/options-resolver[v4.0.4].
```

**Comment by aequasi** [comment]
Give `dev-develop` a try, just upped the version requirements.

**Comment by keesh7663** [comment]
I'm a bit leery about using a development branch in production (where this is going to be in a week or so).  Is it stable?

**Comment by keesh7663** [comment]
Well, compared branches and it seems fine.  `dev-develop` installed fine, but I'm still going to have to wait until those changes make it to master since that's what the Laravel wrapper requires.  Thanks for the quick response!

**Comment by aequasi** [comment]
https://github.com/restcord/restcord/releases/tag/0.2.2
