### ISSUE TITLE
add member to guild

### ISSUE THREAD

**Issue by Feerko** [restcord/restcord#47]
```vbs
<?php

  require __DIR__ . '/vendor/autoload.php';

  use Wohali\OAuth2\Client\Provider\Discord;
  use RestCord\DiscordClient;

  session_start();

  $provider = new \Wohali\OAuth2\Client\Provider\Discord([
      'clientId' => 'xxx',
      'clientSecret' => 'xxx',
      'redirectUri' => 'xxx'
  ]);

  if (!isset($_GET['code'])) {

      $authUrl = $provider->getAuthorizationUrl();
      $_SESSION['oauth2state'] = $provider->getState();
      header('Location: ' . $authUrl);

  } elseif (empty($_GET['state']) || ($_GET['state'] !== $_SESSION['oauth2state'])) {

      unset($_SESSION['oauth2state']);
      exit('Invalid state');

  } else {

    $token = $provider->getAccessToken('authorization_code', [
        'code' => $_GET['code']
    ]);

    try {

      $user = $provider->getResourceOwner($token);
      $discord_id = $user->getId();
      $args = [
        'guild.id' => xxx,
        'user.id' => intval($discord_id),
        'access_token' => $token
      ];

      $client = new DiscordClient([
        'token' => 'xxx'
      ]);

      var_dump($client->guild->addGuildMember($args));

    } catch (Exception $e) {
      exit("Oh dear... $e");
    }
  }
?>
```

this code doesn't work for me, I get 'forbidden' from discord's api

**Comment by Feerko** [comment]
Oh dear... GuzzleHttp\Exception\ClientException: Client error: `PUT https://discordapp.com/api/v6/guilds/425673791549472780/members/371532684716933120` resulted in a `400 BAD REQUEST` response: (truncated...)

**Comment by hiveliberty** [comment]
This is my function from my class for add user to discord and it works correct.
Nick and roles is optional params.

```php
	public function user_add($discord_id, $token, $nick = null, $roles = null) {
		$response = $this->client->guild->addGuildMember([
			'guild.id' => (int)$this->config['guild_id'],
			'user.id' => (int)$discord_id,
			'access_token' => (string)$token,
			'nick' => (string)$nick,
			'roles' => $roles
		]);
		return $response;
	}
```

**Comment by Feerko** [comment]
I get this:

`
GuzzleHttp\Exception\ClientException: Client error: `PUT https://discordapp.com/api/v6/guilds/422016694408577025/members/373878398168072193` resulted in a `400 BAD REQUEST` response: (truncated...) in /var/www/discord/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113 Stack trace: #0 /var/www/discord/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 /var/www/discord/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 /var/www/discord/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #3 /var/www/discord/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #4 /var/www/discord/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(96): GuzzleHttp\Promise\TaskQueue->run() #5 /var/www/discord/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(123): GuzzleHttp\Handler\CurlMultiHandler->tick() #6 /var/www/discord/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Handler\CurlMultiHandler->execute(true) #7 /var/www/discord/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn() #8 /var/www/discord/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending() #9 /var/www/discord/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList() #10 /var/www/discord/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #11 /var/www/discord/vendor/guzzlehttp/promises/src/Coroutine.php(65): GuzzleHttp\Promise\Promise->wait() #12 /var/www/discord/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\Coroutine->GuzzleHttp\Promise\{closure}(true) #13 /var/www/discord/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn() #14 /var/www/discord/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #15 /var/www/discord/vendor/guzzlehttp/promises/src/Coroutine.php(85): GuzzleHttp\Promise\Promise->wait(true) #16 /var/www/discord/vendor/guzzlehttp/command/src/ServiceClient.php(77): GuzzleHttp\Promise\Coroutine->wait() #17 /var/www/discord/vendor/guzzlehttp/command/src/ServiceClient.php(153): GuzzleHttp\Command\ServiceClient->execute(Object(GuzzleHttp\Command\Command)) #18 /var/www/discord/vendor/restcord/restcord/src/OverriddenGuzzleClient.php(87): GuzzleHttp\Command\ServiceClient->__call('addGuildMember', Array) #19 /var/www/discord/index.php(51): RestCord\OverriddenGuzzleClient->__call('addGuildMember', Array) #20 {main} Next GuzzleHttp\Command\Exception\CommandClientException: There was an error executing the addGuildMember command: Client error: `PUT https://discordapp.com/api/v6/guilds/422016694408577025/members/373878398168072193` resulted in a `400 BAD REQUEST` response: (truncated...) in /var/www/discord/vendor/guzzlehttp/command/src/Exception/CommandException.php:57 Stack trace: #0 /var/www/discord/vendor/guzzlehttp/command/src/ServiceClient.php(179): GuzzleHttp\Command\Exception\CommandException::fromPrevious(Object(GuzzleHttp\Command\Command), Object(GuzzleHttp\Exception\ClientException)) #1 [internal function]: GuzzleHttp\Command\ServiceClient->GuzzleHttp\Command\{closure}() #2 /var/www/discord/vendor/guzzlehttp/promises/src/Coroutine.php(142): Generator->throw(Object(GuzzleHttp\Exception\ClientException)) #3 /var/www/discord/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Promise\Coroutine->_handleFailure(Object(GuzzleHttp\Exception\ClientException)) #4 /var/www/discord/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(2, Object(GuzzleHttp\Exception\ClientException), Array) #5 /var/www/discord/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #6 /var/www/discord/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(96): GuzzleHttp\Promise\TaskQueue->run() #7 /var/www/discord/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(123): GuzzleHttp\Handler\CurlMultiHandler->tick() #8 /var/www/discord/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Handler\CurlMultiHandler->execute(true) #9 /var/www/discord/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn() #10 /var/www/discord/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending() #11 /var/www/discord/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList() #12 /var/www/discord/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #13 /var/www/discord/vendor/guzzlehttp/promises/src/Coroutine.php(65): GuzzleHttp\Promise\Promise->wait() #14 /var/www/discord/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\Coroutine->GuzzleHttp\Promise\{closure}(true) #15 /var/www/discord/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn() #16 /var/www/discord/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #17 /var/www/discord/vendor/guzzlehttp/promises/src/Coroutine.php(85): GuzzleHttp\Promise\Promise->wait(true) #18 /var/www/discord/vendor/guzzlehttp/command/src/ServiceClient.php(77): GuzzleHttp\Promise\Coroutine->wait() #19 /var/www/discord/vendor/guzzlehttp/command/src/ServiceClient.php(153): GuzzleHttp\Command\ServiceClient->execute(Object(GuzzleHttp\Command\Command)) #20 /var/www/discord/vendor/restcord/restcord/src/OverriddenGuzzleClient.php(87): GuzzleHttp\Command\ServiceClient->__call('addGuildMember', Array) #21 /var/www/discord/index.php(51): RestCord\OverriddenGuzzleClient->__call('addGuildMember', Array) #22 {main}
`

**Comment by hiveliberty** [comment]
Does your bot have the max permissions and its role at the top of all other?

**Comment by Feerko** [comment]
<img width="740" alt="zrzut ekranu 2018-03-22 o 09 29 32" src="https://user-images.githubusercontent.com/16988054/37761276-7e2199e6-2db9-11e8-854b-048a5ac78116.png">
When i'm select guilds.join i get Invalid State


<img width="737" alt="zrzut ekranu 2018-03-22 o 09 29 28" src="https://user-images.githubusercontent.com/16988054/37761277-7f536f4c-2db9-11e8-8583-570616a5b421.png">

**Comment by hiveliberty** [comment]
guilds.join - this is your issue
You must use this scope.

My example:
```php
$discord_url = "https://discordapp.com/api/oauth2/authorize?client_id=" . $config_discord["client_id"] . "&redirect_uri=" . $config_discord['callback_url'] . "&response_type=code" . "&scope=identify guilds.join" . "&state=" . $_SESSION['discord_state'];
```
Hmm.. I don't use 'bot' scope.. But my service works fine.

But I asked about bot permissions on your discord server too..

**Comment by Feerko** [comment]
My bot has all permissions on server, I'm added this code:

```vbs
      $options = [
          'scope' => ['guilds.join']
      ];
      $authUrl = $provider->getAuthorizationUrl($options);
      $_SESSION['oauth2state'] = $provider->getState();
      header('Location: ' . $authUrl);
```

and still doesn't work

**Comment by hiveliberty** [comment]
This scope must be in the link that users are passing through, not in oathu2 provider..
oAuth2 provider is used for exchange returned code to access token and refresh token for user.

**Comment by Feerko** [comment]
<img width="302" alt="zrzut ekranu 2018-03-22 o 10 53 25" src="https://user-images.githubusercontent.com/16988054/37763414-48e01fae-2dbf-11e8-9a65-385345f22157.png">

**Comment by hiveliberty** [comment]
Can you show all your code? (not here of course - link to repo, example)

**Comment by hiveliberty** [comment]
I found why for me all works fine.. I did not update restcord to latest version..
Latest version has some issue with "private function convertResponseToResult"

**Comment by hiveliberty** [comment]
I found that issue is related to the version of guzzlehttp.

**Comment by Feerko** [comment]
@hiveliberty can you make small code for me? I can pay for your time. Can you give your discord?

**Comment by hiveliberty** [comment]
I tried to debug your code and don't understand why guzzle causes exception.. This is strange, because same code works in other "place".. 0_o

**Comment by hiveliberty** [comment]
@Feerko, I debugged your example. Authorization is working properly. Exception causes only if owner tries to sign in.

**Comment by d3vit** [comment]
So to get this straight, you first have to grab an OAuth token from the user (John Doe) that is requesting to join, then you can make the call?

Basic flow:

1.) User clicks button
2.) User authorizes application
3.) OAuth token is returned
4.) addGuildMember is called using John Doe's auth token
5.) Member is added to channel

Correct?

**Comment by RaflyLesmana3003** [comment]
There was an error executing the addGuildMember command: Client error: `PUT https://discordapp.com/api/v6/guilds/xxx/members/xxx` resulted in a `403 Forbidden` response 

anyone please help me...., why a got this error?

this is my code: 
$discord->guild->addGuildMember([
            'guild.id' => intval($request->get('guild_id')),
            'user.id' => "--- id from user discord login ---",
            'access_token' => "--- token from user discord login ---"
]);

**Comment by oliverschloebe** [comment]
Try changing
```php
'guild.id' => intval($request->get('guild_id')),
```
to
```php
'guild.id' => (int)$request->get('guild_id'),
```

**Comment by RaflyLesmana3003** [comment]
> Try changing
> 
> ```
> 'guild.id' => intval($request->get('guild_id')),
> ```
> 
> to
> 
> ```
> 'guild.id' => (int)$request->get('guild_id'),
> ```

im sorry, is working now....
my oauth scope is only get identity and email,
and is must include guild.joins scope

fun fact i ask the restcord developer by email hehehe...

**Comment by hugzho** [comment]
> > Try changing
> > ```
> > 'guild.id' => intval($request->get('guild_id')),
> > ```
> > 
> > 
> > to
> > ```
> > 'guild.id' => (int)$request->get('guild_id'),
> > ```
> 
> im sorry, is working now....
> my oauth scope is only get identity and email,
> and is must include guild.joins scope
> 
> fun fact i ask the restcord developer by email hehehe...

Can you send the working PHP code? Please, I have been stuck on this for a while

**Comment by RaflyLesmana3003** [comment]
> > > Try changing
> > > ```
> > > 'guild.id' => intval($request->get('guild_id')),
> > > ```
> > > 
> > > 
> > > to
> > > ```
> > > 'guild.id' => (int)$request->get('guild_id'),
> > > ```
> > 
> > 
> > im sorry, is working now....
> > my oauth scope is only get identity and email,
> > and is must include guild.joins scope
> > fun fact i ask the restcord developer by email hehehe...
> 
> Can you send the working PHP code? Please, I have been stuck on this for a while

![Screenshot_2020-03-23 Discord Developer Portal — API Docs for Bots and Developers](https://user-images.githubusercontent.com/42396310/77327703-8320ea00-6d13-11ea-8597-105d48b22d9c.png)
 in my case, i only oauth scope use identity email, but if you want to join guild you must use guild.join scope.

in my project i use laravel with ouath from socialite discord composer package, by default socialite only use identity and email, and you must add guild.joins scope manually, you can add guild.joins in vendor->scocialiteproviders->discord->provider.php.

> protected $scopes = [
>         'identify',
>         'email',
> 	'guilds.join',
>     ];

if you not use socialite you must search this file.
and if you only use oauth from discord it self you must check guild.join scope, like this

![Screenshot_2020-03-23 Discord Developer Portal — API Docs for Bots and Developers](https://user-images.githubusercontent.com/42396310/77328897-1d356200-6d15-11ea-9d30-18ff5f14c3cd.png)
