### ISSUE TITLE
service_description.json - "invite" responseTypes

### ISSUE THREAD

**Issue by donkkill13** [restcord/restcord#6]
Currently, in the commands `"getInvite"`, `"deleteInvite"`, `"acceptInvite"`, the responseTypes have the name `"invite object"` which should be `"invite"` since `"invite object"` throws an error, the model doesn't exist.

The full commands throwing the error are:

`"$client->invite->getInvite()"`
`"$client->invite->deleteInvite()"`
`"$client->invite->acceptInvite()"`

**Comment by aequasi** [comment]
Partially resolved with: https://github.com/aequasi/discord-service-definition-generator/commit/d8500bce11a3c4316dade3ca0acfaf079e3dd936

Need to finish the fix in restcord

**Comment by sn0opy** [comment]
Looks like I just ran into the exact same issue. Any ETA on a release?

**Comment by aequasi** [comment]
Try the dev-develop branch

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
