### ISSUE TITLE
Fatal error with getChannelMessages()

### ISSUE THREAD

**Issue by nachochips00** [restcord/restcord#67]
Hi guys. Having some troubles with getChannelMessages(). In the documentation for this function it says only the 'channel.id' parameter is required, but when I try to run it, it says the other parameters should be an integer?

PHP-code:

`<?php

include __DIR__.'/vendor/autoload.php';

use RestCord\DiscordClient;

$discord = new DiscordClient(['token' => 'token_here']);

$channel_messages = $discord->channel->getChannelMessages(['channel.id' => 386989270566436887, 'limit' => 50]);

var_dump($channel_messages);

?>`

LOG:

`Fatal error: Uncaught exception 'GuzzleHttp\Command\Exception\CommandException' with message 'Validation errors: [around] must be of type integer
[before] must be of type integer
[after] must be of type integer' in /Users/X/Git/tradingsystem/restcord/vendor/guzzlehttp/guzzle-services/src/Handler/ValidatedDescriptionHandler.php:76
Stack trace:
#0 /Users/X/Git/tradingsystem/restcord/vendor/guzzlehttp/command/src/ServiceClient.php(85): GuzzleHttp\Command\Guzzle\Handler\ValidatedDescriptionHandler->GuzzleHttp\Command\Guzzle\Handler\{closure}(Object(GuzzleHttp\Command\Command))
#1 /Users/X/Git/tradingsystem/restcord/vendor/guzzlehttp/command/src/ServiceClient.php(77): GuzzleHttp\Command\ServiceClient->executeAsync(Object(GuzzleHttp\Command\Command))
#2 /Users/X/Git/tradingsystem/restcord/vendor/guzzlehttp/command/src/ServiceClient.php(153): GuzzleHttp\Command\ServiceClient->execute(Object(GuzzleHttp\Command\Command))
#3 /Users/X/Git/tradingsystem/restcord/run.php(9): GuzzleHttp\Command\ServiceClient->_ in /Users/X/Git/tradingsystem/restcord/vendor/guzzlehttp/guzzle-services/src/Handler/ValidatedDescriptionHandler.php on line 76`

**Comment by OliverSchloebe** [comment]
Updating RestCord via Composer fixed the issue for me.
