### ISSUE TITLE
service_description.json - "user" category - URL error

### ISSUE THREAD

**Issue by donkkill13** [restcord/restcord#7]
Currently, the commands `"getCurrentUser"`, `"modifyCurrentUser"`, `"getCurrentUserGuilds"`, `"leaveGuild"`, `"getUserDms"`, `"createDm"`, `"createGroupDm"`, `"getUsersConnections"`, all contain the url `"/users//@me"` which should be `"/users/@me"` instead.

Full Paths:

`"$client->user->getCurrentUser()"`
`"$client->user->modifyCurrentUser()"`
`"$client->user->getCurrentUserGuilds()"`
`"$client->user->leaveGuild()"`
`"$client->user->getUserDms()"`
`"$client->user->createDm()"`
`"$client->user->createGroupDm()"`
`"$client->user->getUsersConnections()"`

**Comment by aequasi** [comment]
Partially resolved with: https://github.com/aequasi/discord-service-definition-generator/commit/d8500bce11a3c4316dade3ca0acfaf079e3dd936

Need to finish the fix in restcord
