### ISSUE TITLE
service_description.json - "user" category - DM URL errors

### ISSUE THREAD

**Issue by donkkill13** [restcord/restcord#8]
Currently, the commands `"getUserDms"`, `"createDm"`, `"createGroupDm"`, have the urls `"/users//@me"`, which should be `"/users/@me/channels"` so it works.

Full Commands:

`"$client->user->getUserDms()"`
`"$client->user->createDm()"`
`"$client->user->createGroupDm()"`

**Comment by aequasi** [comment]
Partially resolved with: https://github.com/aequasi/discord-service-definition-generator/commit/d8500bce11a3c4316dade3ca0acfaf079e3dd936

Need to finish the fix in restcord
