### ISSUE TITLE
service_description.json - "user" category - "leaveGuild" Missing Parameters

### ISSUE THREAD

**Issue by donkkill13** [restcord/restcord#9]
`"leaveGuild"` currently is missing required parameters and the url is wrong.

Currently the url is `"/users//@me"` which should be `"/users/@me/guilds/{guild.id}"`.

The parameters should include the guild.id, which it currently has no parameters.

Full Command:

`"$client->user->leaveGuild()"`

**Comment by aequasi** [comment]
Partially resolved with: https://github.com/aequasi/discord-service-definition-generator/commit/d8500bce11a3c4316dade3ca0acfaf079e3dd936

Need to finish the fix in restcord
